# Generated by Django 5.2.8 on 2025-11-16 23:40

"""
This migration previously created `accounts.CustomUser`.

The project has moved `CustomUser` into the `bookshelf` app. To avoid
import-time errors during development while the migrations are being
reworked, this migration file has been turned into a no-op placeholder.

IMPORTANT: Review and rebuild your migrations to reflect the model move.
See Django docs on squashing/moving models between apps.
"""

from django.db import migrations


class Migration(migrations.Migration):
    # placeholder migration left intentionally empty after model move
    initial = False
    dependencies = []
    operations = []
